import functions
from classes.User import *
from functions import *
from dbFunctions import *
import mysql.connector
import sys
from classes.colors import *
sys.path.append("../../usersManagementPY")
while True:
    ##MAIN MENU
    print (f"{bcolors.Cyan}#############################################################################")
    print (f"{bcolors.Cyan}########                                                             ########")
    print (f"{bcolors.Cyan}######## "f"{bcolors.Purple}            GESTION UTILISATEUR IN PYTHON  " f"{bcolors.Cyan}                 ########")
    print (f"{bcolors.Cyan}######## ----------------------------------------------------------- ########")
    print (f"{bcolors.Cyan}######## "f"{bcolors.Purple}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.Cyan}      ########")
    print (f"{bcolors.Cyan}######## ----------------------------------------------------------- ########")
    print (f"{bcolors.Cyan}########                                                             ########")
    print (f"{bcolors.Cyan}######## "f"{bcolors.Purple}                  Choose a option: " f"{bcolors.Cyan}                         ########")
    print (f"{bcolors.Cyan}########                                                             ########")
    print (f"{bcolors.Cyan}######## "f"{bcolors.Purple}             1) ADMIN        |   2) USER "f" {bcolors.Cyan}                  ########")
    print (f"{bcolors.Cyan}########                                                             ########")
    print (f"{bcolors.Cyan}######## "f"{bcolors.Purple}                        3) Exit     "f" {bcolors.Cyan}                       ########")
    print (f"{bcolors.Cyan}########                                                             ########")
    print (f"{bcolors.Cyan}########                                                             ########")
    print (f"{bcolors.Cyan}#############################################################################")
    number = input(f"{bcolors.BYellow}Enter a number from 1 to 3: ")
    #Admin
    if int(number) == 1:
        print(f"{bcolors.pink}#############################################################################")
        print(f"{bcolors.pink}######## "f"{bcolors.Blue}                     WELCOME ADMIN  " f"{bcolors.pink}                        ########")
        print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
        print(f"{bcolors.pink}######## "f"{bcolors.Blue}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.pink}      ########")
        print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
        print(f"{bcolors.pink}######## "f"{bcolors.Blue}                     Login page  " f"{bcolors.pink}                           ########")
        print(f"{bcolors.pink}########                                                             ########")
        while True:
            admin = sign_in_as_admin(input(f"{'Enter the login:': >40}"), input(f"{'Enter the password:': >40}"))
            if not admin:
                continue
            else:
                break
        print(f"{bcolors.pink}########                                                             ########")
        print(f"{bcolors.pink}########                                                             ########")
        print(f"{bcolors.pink}#############################################################################")
        while True:
            print(f"{bcolors.pink}#############################################################################")
            print(f"{bcolors.pink}########                                                             ########")
            print(f"{bcolors.pink}######## "f"{bcolors.Blue}                     WELCOME ADMIN  " f"{bcolors.pink}                        ########")
            print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
            print(f"{bcolors.pink}######## "f"{bcolors.Blue}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.pink}      ########")
            print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
            print(f"{bcolors.pink}########                                                             ########")
            print(f"{bcolors.pink}######## "f"{bcolors.Blue}                  Choose a option: " f"{bcolors.pink}                         ########")
            print(f"{bcolors.pink}########                                                             ########")
            print(f"{bcolors.pink}######## "f"{bcolors.Blue}    1) Add a user        |  3) Search a user   " f"{bcolors.pink}             ########")
            print(f"{bcolors.pink}######## "f"{bcolors.Blue}    2) Modify a user     |  4) Delete a user   " f"{bcolors.pink}             ########")
            print(f"{bcolors.pink}########                                                             ########")
            print(f"{bcolors.pink}######## "f"{bcolors.Blue}                   5) Exit                      " f"{bcolors.pink}            ########")
            print(f"{bcolors.pink}########                                                             ########")
            print(f"{bcolors.pink}########                                                             ########")
            print(f"{bcolors.pink}#############################################################################")
            number = input(f"{bcolors.BYellow}Enter a number from 1 to 5: ")
            # Add User
            if int(number) == 1:
                print(f"{bcolors.pink}#############################################################################")
                print(f"{bcolors.pink}########                                                             ########")
                print(f"{bcolors.pink}######## "f"{bcolors.Blue}                     WELCOME ADMIN  " f"{bcolors.pink}                        ########")
                print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                print(f"{bcolors.pink}######## "f"{bcolors.Blue}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.pink}      ########")
                print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                print(f"{bcolors.pink}########                                                             ########")
                print( f"{bcolors.pink}######## "f"{bcolors.Blue}                  Add User : " f"{bcolors.pink}                               ########")
                print(f"{bcolors.pink}########                                                             ########")
                admin.add_user(input(f"{'Enter last name :': >40}"),
                               input(f"{'Enter first name :': >40}"),
                               input(f"{'Enter date of birth :': >40}"),
                               input(f"{'Enter place of birth :': >40}"),
                               input(f"{'Enter email:': >40}"))
                print(f"{bcolors.pink}########                                                             ########")
                print(f"{bcolors.pink}########                                                             ########")
                print(f"{bcolors.pink}########                                                             ########")
                print(f"{bcolors.pink}#############################################################################")
            # Modify User
            elif int(number) == 2:
                print(f"{bcolors.pink}#############################################################################")
                print(f"{bcolors.pink}########                                                             ########")
                print(f"{bcolors.pink}######## "f"{bcolors.Blue}                     WELCOME ADMIN  " f"{bcolors.pink}                        ########")
                print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                print(f"{bcolors.pink}######## "f"{bcolors.Blue}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.pink}      ########")
                print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                print(f"{bcolors.pink}########                                                             ########")
                print(f"{bcolors.pink}######## "f"{bcolors.Blue}                  Modify User : " f"{bcolors.pink}                            ########")
                print(f"{bcolors.pink}########                                                             ########")
                admin.list_all_user()
                userId = input("Which user you want to modify (enter id): ")
                admin.list_user(userId)
                while True:
                    print(f"{bcolors.pink}#############################################################################")
                    print(f"{bcolors.pink}########                                                             ########")
                    print(f"{bcolors.pink}######## "f"{bcolors.Blue}                     WELCOME ADMIN  " f"{bcolors.pink}                        ########")
                    print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                    print(f"{bcolors.pink}######## "f"{bcolors.Blue}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.pink}      ########")
                    print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                    print(f"{bcolors.pink}########                                                             ########")
                    print(f"{bcolors.pink}######## "f"{bcolors.Blue}       Choose something to modify: " f"{bcolors.pink}                          ########")
                    print(f"{bcolors.pink}########                                                             ########")
                    print(f"{bcolors.pink}######## "f"{bcolors.Blue}       1) Lastname     |  3) Date of Birth      " f"{bcolors.pink}             ########")
                    print(f"{bcolors.pink}######## "f"{bcolors.Blue}       2) Firstname    |  4) Country of Birth   " f"{bcolors.pink}             ########")
                    print(f"{bcolors.pink}######## "f"{bcolors.Blue}       5) Email        |  6) Department          " f"{bcolors.pink}            ########")
                    print(f"{bcolors.pink}######## "f"{bcolors.Blue}              7) Generate Password               " f"{bcolors.pink}            ########")
                    print(f"{bcolors.pink}########                                                             ########")
                    print(f"{bcolors.pink}########                                                             ########")
                    print(f"{bcolors.pink}#############################################################################")
                    choice = input(f"{bcolors.BYellow}Enter a number from 1 to 7: ")
                    #Lastname
                    if int(choice) == 1:
                        print(f"{bcolors.pink}#############################################################################")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}######## "f"{bcolors.Blue}                     WELCOME ADMIN  " f"{bcolors.pink}                        ########")
                        print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                        print(f"{bcolors.pink}######## "f"{bcolors.Blue}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.pink}      ########")
                        print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}######## "f"{bcolors.Blue}           Modify Lastname : " f"{bcolors.pink}                               ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        admin.modify_user_lastname(input("Enter new lastname:"), userId)
                        admin.list_user(userId)
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}#############################################################################")
                    # Firstname
                    elif int(choice) == 2:
                        print(f"{bcolors.pink}#############################################################################")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}######## "f"{bcolors.Blue}                     WELCOME ADMIN  " f"{bcolors.pink}                        ########")
                        print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                        print(f"{bcolors.pink}######## "f"{bcolors.Blue}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.pink}      ########")
                        print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}######## "f"{bcolors.Blue}          Modify Firstname : " f"{bcolors.pink}                               ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        admin.modify_user_firstname(input("Enter new firstname:"), userId)
                        admin.list_user(userId)
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}#############################################################################")
                    # Date of birth
                    elif int(choice) == 3:
                        print(f"{bcolors.pink}#############################################################################")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}######## "f"{bcolors.Blue}                     WELCOME ADMIN  " f"{bcolors.pink}                        ########")
                        print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                        print(f"{bcolors.pink}######## "f"{bcolors.Blue}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.pink}      ########")
                        print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}######## "f"{bcolors.Blue}      Modify Date of birth : " f"{bcolors.pink}                               ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        admin.modify_user_dob(input("Enter new date of birth:"), userId)
                        admin.list_user(userId)
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}#############################################################################")
                    # Country of Birth
                    elif int(choice) == 4:
                        print(f"{bcolors.pink}#############################################################################")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}######## "f"{bcolors.Blue}                     WELCOME ADMIN  " f"{bcolors.pink}                        ########")
                        print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                        print(f"{bcolors.pink}######## "f"{bcolors.Blue}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.pink}      ########")
                        print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}######## "f"{bcolors.Blue}   Modify Country of birth : " f"{bcolors.pink}                               ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        admin.modify_user_pob(input("Enter new country of birth:"), userId)
                        admin.list_user(userId)
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}#############################################################################")
                    # Email
                    elif int(choice) == 5:
                        print(f"{bcolors.pink}#############################################################################")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}######## "f"{bcolors.Blue}                     WELCOME ADMIN  " f"{bcolors.pink}                        ########")
                        print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                        print(f"{bcolors.pink}######## "f"{bcolors.Blue}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.pink}      ########")
                        print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}######## "f"{bcolors.Blue}              Modify Email : " f"{bcolors.pink}                               ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        admin.modify_user_email(input("Enter new email:"), userId)
                        admin.list_user(userId)
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}#############################################################################")
                    # Change department
                    elif int(choice) == 6:
                        print(f"{bcolors.pink}#############################################################################")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}######## "f"{bcolors.Blue}                     WELCOME ADMIN  " f"{bcolors.pink}                        ########")
                        print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                        print(f"{bcolors.pink}######## "f"{bcolors.Blue}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.pink}      ########")
                        print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}######## "f"{bcolors.Blue}              Modify right : " f"{bcolors.pink}                               ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        admin.change_rights(userId)
                        admin.list_user(userId)
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}#############################################################################")
                    # Generate pwd
                    elif int(choice) == 7:
                        print(f"{bcolors.pink}#############################################################################")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}######## "f"{bcolors.Blue}                     WELCOME ADMIN  " f"{bcolors.pink}                        ########")
                        print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                        print(f"{bcolors.pink}######## "f"{bcolors.Blue}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.pink}      ########")
                        print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}######## "f"{bcolors.Blue}              Generate password : " f"{bcolors.pink}                          ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        admin.generate_user_pwd(userId)
                        admin.list_user(userId)
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}#############################################################################")
                    else:
                        print("Mauvais choix")
                        break
            # Search user
            elif int(number) == 3:
                while True:
                    print(f"{bcolors.pink}#############################################################################")
                    print(f"{bcolors.pink}########                                                             ########")
                    print(f"{bcolors.pink}######## "f"{bcolors.Blue}                     WELCOME ADMIN  " f"{bcolors.pink}                        ########")
                    print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                    print(f"{bcolors.pink}######## "f"{bcolors.Blue}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.pink}      ########")
                    print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                    print(f"{bcolors.pink}########                                                             ########")
                    print(f"{bcolors.pink}######## "f"{bcolors.Blue}       Search by: " f"{bcolors.pink}                         ########")
                    print(f"{bcolors.pink}########                                                             ########")
                    print(f"{bcolors.pink}######## "f"{bcolors.Blue}       1) Lastname     |  3) Date of Birth      " f"{bcolors.pink}             ########")
                    print(f"{bcolors.pink}######## "f"{bcolors.Blue}       2) Firstname    |  4) Country of Birth   " f"{bcolors.pink}             ########")
                    print(f"{bcolors.pink}######## "f"{bcolors.Blue}                    5) Email                    " f"{bcolors.pink}             ########")
                    print(f"{bcolors.pink}########                                                             ########")
                    print(f"{bcolors.pink}########                                                             ########")
                    print(f"{bcolors.pink}#############################################################################")
                    choice = input(f"{bcolors.BYellow}Enter a number from 1 to 5: ")
                    # Lastname
                    if int(choice) == 1:
                        print(f"{bcolors.pink}#############################################################################")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(
                            f"{bcolors.pink}######## "f"{bcolors.Blue}                     WELCOME ADMIN  " f"{bcolors.pink}                        ########")
                        print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                        print(
                            f"{bcolors.pink}######## "f"{bcolors.Blue}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.pink}      ########")
                        print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(
                            f"{bcolors.pink}######## "f"{bcolors.Blue}           Search Lastname : " f"{bcolors.pink}                               ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        admin.search_lastname(input("Enter lastname you are searching for: "))
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}#############################################################################")
                    # Firstname
                    elif int(choice) == 2:
                        print(f"{bcolors.pink}#############################################################################")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(
                            f"{bcolors.pink}######## "f"{bcolors.Blue}                     WELCOME ADMIN  " f"{bcolors.pink}                        ########")
                        print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                        print(
                            f"{bcolors.pink}######## "f"{bcolors.Blue}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.pink}      ########")
                        print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(
                            f"{bcolors.pink}######## "f"{bcolors.Blue}          Search Firstname : " f"{bcolors.pink}                               ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        admin.search_firstname(input("Enter firstname you are searching for: "))
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}#############################################################################")
                    # Date of birth
                    elif int(choice) == 3:
                        print(f"{bcolors.pink}#############################################################################")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}######## "f"{bcolors.Blue}                     WELCOME ADMIN  " f"{bcolors.pink}                        ########")
                        print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                        print(f"{bcolors.pink}######## "f"{bcolors.Blue}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.pink}      ########")
                        print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}######## "f"{bcolors.Blue}      Search Date of birth : " f"{bcolors.pink}                               ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        admin.search_dob(input("Enter date of birth you are searching for: "))
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}#############################################################################")
                    # Country of birth
                    elif int(choice) == 4:
                        print(f"{bcolors.pink}#############################################################################")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}######## "f"{bcolors.Blue}                     WELCOME ADMIN  " f"{bcolors.pink}                        ########")
                        print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                        print(f"{bcolors.pink}######## "f"{bcolors.Blue}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.pink}      ########")
                        print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}######## "f"{bcolors.Blue}   Search Country of birth : " f"{bcolors.pink}                               ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        admin.search_pob(input("Enter country of birth you are searching for: "))
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}#############################################################################")
                    # Email
                    elif int(choice) == 5:
                        print(f"{bcolors.pink}#############################################################################")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}######## "f"{bcolors.Blue}                     WELCOME ADMIN  " f"{bcolors.pink}                        ########")
                        print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                        print(f"{bcolors.pink}######## "f"{bcolors.Blue}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.pink}      ########")
                        print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}######## "f"{bcolors.Blue}              Search Email : " f"{bcolors.pink}                               ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        admin.search_email(input("Enter email you are searching for: "))
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}########                                                             ########")
                        print(f"{bcolors.pink}#############################################################################")
                    else:
                        print("Mauvais choix")
                        break
            # Delete User
            elif int(number) == 4:
                print(f"{bcolors.pink}#############################################################################")
                print(f"{bcolors.pink}########                                                             ########")
                print(f"{bcolors.pink}######## "f"{bcolors.Blue}                     WELCOME ADMIN  " f"{bcolors.pink}                        ########")
                print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                print(f"{bcolors.pink}######## "f"{bcolors.Blue}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.pink}      ########")
                print(f"{bcolors.pink}######## ----------------------------------------------------------- ########")
                print(f"{bcolors.pink}########                                                             ########")
                print(f"{bcolors.pink}######## "f"{bcolors.Blue}                  Delete User : " f"{bcolors.pink}                            ########")
                print(f"{bcolors.pink}########                                                             ########")
                admin.list_all_user()
                userId = input("Which user you want to modify (enter id): ")
                if input("Are you sure to delete %s (1 for yes)" %(userId)) == "1":
                    admin.remove_user(userId)
                    admin.list_all_user()
                else:
                    print("Thank god you didn't remove him")
            else:
                print("Mauvais choix")
                break
    # Worker
    elif int(number) == 2:
        print(f"{bcolors.BBlack}#############################################################################")
        print(f"{bcolors.BBlack}########                                                             ########")
        print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}                          WELCOME USER                  " f"{bcolors.BBlack}    ########")
        print(f"{bcolors.BBlack}######## ----------------------------------------------------------- ########")
        print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.BBlack}      ########")
        print(f"{bcolors.BBlack}######## ----------------------------------------------------------- ########")
        print(f"{bcolors.BBlack}########                                                             ########")
        print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}                        Choose a option: " f"{bcolors.BBlack}                   ########")
        print(f"{bcolors.BBlack}########                                                             ########")
        print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}             1) CREATION        |   2) CONNECTION "f" {bcolors.BBlack}         ########")
        print(f"{bcolors.BBlack}########                                                             ########")
        print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}                        3) Exit     "f" {bcolors.BBlack}                       ########")
        print(f"{bcolors.BBlack}########                                                             ########")
        print(f"{bcolors.BBlack}########                                                             ########")
        print(f"{bcolors.BBlack}#############################################################################")
        choice = input(f"{bcolors.BYellow}Enter a number from 1 to 3: ")
        # creation worker
        if int(choice) == 1:
            print(f"{bcolors.BBlack}#############################################################################")
            print(f"{bcolors.BBlack}########                                                             ########")
            print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}                     WELCOME USER  " f"{bcolors.BBlack}                         ########")
            print(f"{bcolors.BBlack}######## ----------------------------------------------------------- ########")
            print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.BBlack}      ########")
            print(f"{bcolors.BBlack}######## ----------------------------------------------------------- ########")
            print(f"{bcolors.BBlack}########                                                             ########")
            print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}                  Creation User : " f"{bcolors.BBlack}                           ########")
            print(f"{bcolors.BBlack}########                                                             ########")
            lastname = input("Give lastname: ")
            firstname = input("Give firstname: ")
            dateofbirth = input("Give date of birth: ")
            placeofbirth = input("Give country of  birth: ")
            email = input("Give email: ")
            worker = User(lastname, firstname, dateofbirth, placeofbirth, email)
            create_user(worker)
            print(f"{bcolors.BBlack}########                                                             ########")
            print(f"{bcolors.BBlack}########                                                             ########")
            print(f"{bcolors.BBlack}########                                                             ########")
            print(f"{bcolors.BBlack}#############################################################################")
        # login worker
        elif int(choice) == 2:
            print(f"{bcolors.BBlack}#############################################################################")
            print(f"{bcolors.BBlack}########                                                             ########")
            print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}                     WELCOME USER   " f"{bcolors.BBlack}                        ########")
            print(f"{bcolors.BBlack}######## ----------------------------------------------------------- ########")
            print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.BBlack}      ########")
            print(f"{bcolors.BBlack}######## ----------------------------------------------------------- ########")
            print(f"{bcolors.BBlack}########                                                             ########")
            print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}                  Login : " f"{bcolors.BBlack}                                  ########")
            print(f"{bcolors.BBlack}########                                                             ########")
            while True:
                worker = sign_in_as_worker(input(f"{'Enter the login:': >40}"), input(f"{'Enter the password:': >40}"))
                if not worker:
                    continue
                else:
                    break
            print(f"{bcolors.BBlack}########                                                             ########")
            print(f"{bcolors.BBlack}########                                                             ########")
            print(f"{bcolors.BBlack}########                                                             ########")
            print(f"{bcolors.BBlack}#############################################################################")
            while True:
                # option for  worker
                print(f"{bcolors.BBlack}#############################################################################")
                print(f"{bcolors.BBlack}########                                                             ########")
                print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}                     WELCOME USER   " f"{bcolors.BBlack}                        ########")
                print(f"{bcolors.BBlack}######## ----------------------------------------------------------- ########")
                print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.BBlack}      ########")
                print(f"{bcolors.BBlack}######## ----------------------------------------------------------- ########")
                print(f"{bcolors.BBlack}########                                                             ########")
                print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}                   Choose a option : " f"{bcolors.BBlack}                       ########")
                print(f"{bcolors.BBlack}########                                                             ########")
                print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}      1) My information        |   3) Search a user "f"{bcolors.BBlack}        ########")
                print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}                 2) Modify my password          "f"{bcolors.BBlack}            ########")
                print("########                                                             ########")
                print("########                                                             ########")
                print("#############################################################################")
                choice = input(f"{bcolors.BYellow}Enter 1 to 3:")
                # worker inforation
                if int(choice) == 1:
                    print(f"{bcolors.BBlack}#############################################################################")
                    print(f"{bcolors.BBlack}########                                                             ########")
                    print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}                     WELCOME USER   " f"{bcolors.BBlack}                        ########")
                    print(f"{bcolors.BBlack}######## ----------------------------------------------------------- ########")
                    print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.BBlack}      ########")
                    print(f"{bcolors.BBlack}######## ----------------------------------------------------------- ########")
                    print(f"{bcolors.BBlack}########                                                             ########")
                    print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}                   My information " f"{bcolors.BBlack}                          ########")
                    print(f"{bcolors.BBlack}########                                                             ########")
                    print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}          {worker.get_lastname(): ^30} " f"{bcolors.BBlack}                   ########")
                    print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}          {worker.get_firstname(): ^30} " f"{bcolors.BBlack}                   ########")
                    print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}          {worker.get_dob(): ^30} " f"{bcolors.BBlack}                     ########")
                    print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}          {worker.get_pob(): ^30} " f"{bcolors.BBlack}                     ########")
                    print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}          {worker.get_departement(): ^30} " f"{bcolors.BBlack}                   ########")
                    print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}          {worker.get_email(): ^30} " f"{bcolors.BBlack}                   ########")
                    print(f"{bcolors.BBlack}########                                                             ########")
                    print(f"{bcolors.BBlack}########                                                             ########")
                    print(f"{bcolors.BBlack}#############################################################################")
                # password option for worker
                elif int(choice) == 2:
                    print(f"{bcolors.BBlack}#############################################################################")
                    print(f"{bcolors.BBlack}########                                                             ########")
                    print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}                     WELCOME USER   " f"{bcolors.BBlack}                        ########")
                    print(f"{bcolors.BBlack}######## ----------------------------------------------------------- ########")
                    print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.BBlack}      ########")
                    print(f"{bcolors.BBlack}######## ----------------------------------------------------------- ########")
                    print(f"{bcolors.BBlack}########                                                             ########")
                    print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}                   Choose a option : " f"{bcolors.BBlack}                       ########")
                    print(f"{bcolors.BBlack}########                                                             ########")
                    print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}                   1) Create my password                 " f"{bcolors.BBlack}   ########")
                    print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}                   2) Generate the password     " f"{bcolors.BBlack}            ########")
                    print(f"{bcolors.BBlack}########                                                             ########")
                    print(f"{bcolors.BBlack}########                                                             ########")
                    print(f"{bcolors.BBlack}#############################################################################")
                    choice = input(f"{bcolors.BYellow}Enter a number from 1 to 2: ")
                    # create password for worker
                    if int(choice) == 1:
                        print(f"{bcolors.BBlack}#############################################################################")
                        print(f"{bcolors.BBlack}########                                                             ########")
                        print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}                     WELCOME USER   " f"{bcolors.BBlack}                        ########")
                        print(f"{bcolors.BBlack}######## ----------------------------------------------------------- ########")
                        print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.BBlack}      ########")
                        print(f"{bcolors.BBlack}######## ----------------------------------------------------------- ########")
                        print(f"{bcolors.BBlack}########                                                             ########")
                        print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}                   Create my password : " f"{bcolors.BBlack}                    ########")
                        print(f"{bcolors.BBlack}########                                                             ########")
                        print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}                     Create my password                 " f"{bcolors.BBlack}   ########")
                        worker.set_pwd(input("Enter your new password:"))
                        print(f"{bcolors.BBlack}########                                                             ########")
                        print(f"{bcolors.BBlack}########                                                             ########")
                        print(f"{bcolors.BBlack}#############################################################################")
                    # generate password for worker
                    elif int(choice) == 2:
                        print(f"{bcolors.BBlack}#############################################################################")
                        print(f"{bcolors.BBlack}########                                                             ########")
                        print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}                     WELCOME USER   " f"{bcolors.BBlack}                        ########")
                        print(f"{bcolors.BBlack}######## ----------------------------------------------------------- ########")
                        print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.BBlack}      ########")
                        print(f"{bcolors.BBlack}######## ----------------------------------------------------------- ########")
                        print(f"{bcolors.BBlack}########                                                             ########")
                        print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}                   Create my password : " f"{bcolors.BBlack}                    ########")
                        print(f"{bcolors.BBlack}########                                                             ########")
                        print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}                     Generate password                  " f"{bcolors.BBlack}   ########")
                        worker.set_random_pwd()
                        print(f"{bcolors.BBlack}########                                                             ########")
                        print(f"{bcolors.BBlack}########                                                             ########")
                        print(f"{bcolors.BBlack}#############################################################################")

                # search choice
                elif int(choice) == 3:
                    while True:
                        print(f"{bcolors.BBlack}#############################################################################")
                        print(f"{bcolors.BBlack}########                                                             ########")
                        print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}                     WELCOME USER   " f"{bcolors.BBlack}                        ########")
                        print(f"{bcolors.BBlack}######## ----------------------------------------------------------- ########")
                        print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.BBlack}      ########")
                        print(f"{bcolors.BBlack}######## ----------------------------------------------------------- ########")
                        print(f"{bcolors.BBlack}########                                                             ########")
                        print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}       Search by: " f"{bcolors.BBlack}                                           ########")
                        print(f"{bcolors.BBlack}########                                                             ########")
                        print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}       1) Lastname     |  3) Date of Birth      " f"{bcolors.BBlack}             ########")
                        print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}       2) Firstname    |  4) Country of Birth   " f"{bcolors.BBlack}             ########")
                        print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}                    5) Email                    " f"{bcolors.BBlack}             ########")
                        print(f"{bcolors.BBlack}########                                                             ########")
                        print(f"{bcolors.BBlack}########                                                             ########")
                        print(f"{bcolors.BBlack}##########################################################################")
                        choice = input(f"{bcolors.BYellow}Enter a number from 1 to 5: ")
                        # Lastname2
                        if int(choice) == 1:
                            print(f"{bcolors.BBlack}#############################################################################")
                            print(f"{bcolors.BBlack}########                                                             ########")
                            print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}                     WELCOME USER   " f"{bcolors.BBlack}                        ########")
                            print(f"{bcolors.BBlack}######## ----------------------------------------------------------- ########")
                            print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.BBlack}      ########")
                            print(f"{bcolors.BBlack}######## ----------------------------------------------------------- ########")
                            print(f"{bcolors.BBlack}########                                                             ########")
                            print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}           Search Lastname : " f"{bcolors.BBlack}                               ########")
                            print(f"{bcolors.BBlack}########                                                             ########")
                            worker.search_lastname(input("Enter lastname you are searching for: "))
                            print(f"{bcolors.BBlack}########                                                             ########")
                            print(f"{bcolors.BBlack}########                                                             ########")
                            print(f"{bcolors.BBlack}########                                                             ########")
                            print(f"{bcolors.BBlack}#############################################################################")
                        # Firstname
                        elif int(choice) == 2:
                            print(f"{bcolors.BBlack}#############################################################################")
                            print(f"{bcolors.BBlack}########                                                             ########")
                            print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}                     WELCOME USER   " f"{bcolors.BBlack}                        ########")
                            print(f"{bcolors.BBlack}######## ----------------------------------------------------------- ########")
                            print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.BBlack}      ########")
                            print(f"{bcolors.BBlack}######## ----------------------------------------------------------- ########")
                            print(f"{bcolors.BBlack}########                                                             ########")
                            print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}          Search Firstname : " f"{bcolors.BBlack}                               ########")
                            print(f"{bcolors.BBlack}########                                                             ########")
                            worker.search_firstname(input("Enter firstname you are searching for: "))
                            print(f"{bcolors.BBlack}########                                                             ########")
                            print(f"{bcolors.BBlack}########                                                             ########")
                            print(f"{bcolors.BBlack}########                                                             ########")
                            print(f"{bcolors.BBlack}#############################################################################")
                        # Date of birth
                        elif int(choice) == 3:
                            print(f"{bcolors.BBlack}#############################################################################")
                            print(f"{bcolors.BBlack}########                                                             ########")
                            print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}                     WELCOME USER   " f"{bcolors.BBlack}                        ########")
                            print(f"{bcolors.BBlack}######## ----------------------------------------------------------- ########")
                            print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.BBlack}      ########")
                            print(f"{bcolors.BBlack}######## ----------------------------------------------------------- ########")
                            print(f"{bcolors.BBlack}########                                                             ########")
                            print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}      Search Date of birth : " f"{bcolors.BBlack}                               ########")
                            print(f"{bcolors.pink}########                                                             ########")
                            worker.search_dob(input("Enter date of birth you are searching for: "))
                            print(f"{bcolors.BBlack}########                                                             ########")
                            print(f"{bcolors.BBlack}########                                                             ########")
                            print(f"{bcolors.BBlack}########                                                             ########")
                            print(f"{bcolors.BBlack}#############################################################################")
                        # Country of birth
                        elif int(choice) == 4:
                            print(f"{bcolors.BBlack}#############################################################################")
                            print(f"{bcolors.BBlack}########                                                             ########")
                            print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}                     WELCOME USER   " f"{bcolors.BBlack}                        ########")
                            print(f"{bcolors.BBlack}######## ----------------------------------------------------------- ########")
                            print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.BBlack}      ########")
                            print(f"{bcolors.BBlack}######## ----------------------------------------------------------- ########")
                            print(f"{bcolors.BBlack}########                                                             ########")
                            print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}   Search Country of birth : " f"{bcolors.BBlack}                               ########")
                            print(f"{bcolors.BBlack}########                                                             ########")
                            worker.search_pob(input("Enter country of birth you are searching for: "))
                            print(f"{bcolors.BBlack}########                                                             ########")
                            print(f"{bcolors.BBlack}########                                                             ########")
                            print(f"{bcolors.BBlack}########                                                             ########")
                            print(f"{bcolors.BBlack}#############################################################################")
                        # Email
                        elif int(choice) == 5:
                            print(f"{bcolors.BBlack}#############################################################################")
                            print(f"{bcolors.BBlack}########                                                             ########")
                            print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}                     WELCOME USER   " f"{bcolors.BBlack}                        ########")
                            print(f"{bcolors.BBlack}######## ----------------------------------------------------------- ########")
                            print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}      Create By : SINGH Manveer & GEORGE Mukilventhan " f"{bcolors.BBlack}      ########")
                            print(f"{bcolors.BBlack}######## ----------------------------------------------------------- ########")
                            print(f"{bcolors.BBlack}########                                                             ########")
                            print(f"{bcolors.BBlack}######## "f"{bcolors.Grey}              Search Email : " f"{bcolors.BBlack}                               ########")
                            print(f"{bcolors.BBlack}########                                                             ########")
                            worker.search_email(input("Enter email you are searching for: "))
                            print(f"{bcolors.BBlack}########                                                             ########")
                            print(f"{bcolors.BBlack}########                                                             ########")
                            print(f"{bcolors.BBlack}########                                                             ########")
                            print(f"{bcolors.BBlack}#############################################################################")
                        else:
                            print("Mauvais choix")
                            break
                else:
                    print("Mauvais choix")
                    break
    else:
        print("Bye")
        break